### ISSUE TITLE
Use HTTP crate

### ISSUE THREAD

**Issue by olanod** [drogue-iot/reqwless#3]
The `http` crate is pretty much the default to use in every HTTP stack and its Request/Response types have generic body types that could be something implementing `embedded_io::asynch::{Read, Write}` for example. It's not `no_std` friendly yet but that could change(https://github.com/hyperium/http/pull/563) although the PR still relies on `alloc` which I'm not sure if it's acceptable for this client.

**Comment by lulf** [comment]
We want to avoid alloc for sure, do you think it's feasible to change http to support that? In any case, I think #2 (using httparse) will at least remove some of the duplication we have in reqwless.

**Comment by olanod** [comment]
It doesn't look trivial to remove the dependency on alloc from http, it relies a lot on [`Bytes`](https://github.com/tokio-rs/bytes/issues/479) and has custom types like the `HeaderMap` which does allocation.

**Comment by rmja** [comment]
I think this can be closed. The http header parsing now uses httparse.
